datas = ["fstat",
    "getpid",
    "mkdir_",
    "mount",
    "openat",
    "uname",
    "waitpid",
    "chdir",
    "dup",
    "exit",
    "getcwd",
    "getppid",
    "mmap",
    "munmap",
    "pipe",
    "sleep",
    "times",
    "unlink",
    "write",
    "clone",
    "dup2",
    "fork",
    "getdents",
    "gettimeofday",
    "open",
    "read",
    "test_echo",
    "umount",
    "wait",
    "yield"]

for data in datas:
    print("\tli a7, SYS_fork\n\tecall\n\tbne a0, zero, after_"+data+"\n\tla a0, "+data+"\n\tla a1, argv_"+data+"\n\tli a7, SYS_exec\n\tecall\nafter_"+data+":\n")